const tutorialSteps = [
  {
    title: "Step 1: Generate a new avatar to start your journey!",
    videoSrc: "./src/videos/step1_generator.mp4",
    description: `With the traits filter you can specify gender, ethnicities and grooms or const the AI random generate a avatar for you. The knobs works like a filter turn on if you want to be specific.  Every time you hit the generate button the AI will give you a new face. Have fun!`,
  },
  {
    title: "Step 2: Switch between conversation & design mode ",
    videoSrc: "./src/videos/step2_switch.mp4",
    description: `Easily switch between conversation and design mode if you change your mind how the avatar should look like. No need to second guest everything  happening in realtime in front of your eyes.`,
  },
  {
    title: "Step 3: Describe your persona in simpel prompt",
    videoSrc: "./src/videos/step3_Prompt.mp4",
    description: `In any moment you can change your mind and reprogram your assistant using simple text prompt powered by ChatGPT. Just type and see how your  assistant reply to your question. Change the conversation language by clicking on the left menu item.`,
  },
  {
    title: "Step 4: Save & Share with your friends",
    videoSrc: "./src/videos/Step4_share.mp4",
    description: `Publish and share your new assistant with your friends. Making it public allow others to comment and like your creation. You can only save if you have enough credits to save your configuration.`,
  },
];

const backgroundAssets = [
  "Back1",
  "Back2",
  "Back3",
  "Back4",
  "Back5",
  "Back6",
  "Back7",
  "Back8",
  "Back9",
  "Back10",
];

const assetNames = [
  "Studio_Softbox",
  "Studio_makeUp",
  "Studio_reblium",
  "Studio_2_Tone",
  "Old",
  "Studio_Dramatic",
  "Studio_CyberRed",
];

const animationNames = [
  "Idle",
  "Catwalk_Female",
  "am_Stand_Idle_Greet_04_Nod",
  "Catwalk_Male",
  "Idle_Subtle",
  "am_Stand_Idle_Greet_08_WaveComeHere",
  "F_ROM",
];

const voiceMappings = {
  "en-US": {
    Samantha: "en-GB-News-G",
    Richard: "en-GB-News-J",
    Emily: "en-GB-News-H",
    John: "en-GB-Neural2-B",
  },
  "nl-NL": {
    Samantha: "nl-NL-Wavenet-D",
    Richard: "nl-NL-Wavenet-C",
    Emily: "nl-NL-Wavenet-E",
    John: "nl-NL-Standard-B",
  },
  "fr-FR": {
    Samantha: "fr-FR-Neural2-A",
    Richard: "fr-FR-Neural2-B",
    Emily: "fr-FR-Neural2-C",
    John: "fr-FR-Neural2-D",
  },
  "es-ES": {
    Samantha: "es-ES-Neural2-C",
    Richard: "es-ES-Neural2-B",
    Emily: "es-ES-Neural2-A",
    John: "es-ES-Neural2-F",
  },
  "ja-JP": {
    Samantha: "ja-JP-Neural2-B",
    Richard: "ja-JP-Neural2-C",
    Emily: "ja-JP-Wavenet-A",
    John: "ja-JP-Neural2-D",
  },
  "de-DE": {
    Samantha: "de-DE-Neural2-A",
    Richard: "de-DE-Neural2-B",
    Emily: "de-DE-Neural2-C",
    John: "de-DE-Neural2-D",
  },
  "cmn-Hans-CN": {
    Samantha: "cmn-CN-Wavenet-D",
    Richard: "cmn-CN-Wavenet-C",
    Emily: "cmn-TW-Wavenet-A",
    John: "cmn-TW-Wavenet-B",
  },
  "yue-Hant-HK": {
    Samantha: "yue-HK-Standard-C",
    Richard: "yue-HK-Standard-D",
    Emily: "yue-HK-Standard-A",
    John: "yue-HK-Standard-B",
  },
  "ar-XA": {
    Samantha: "ar-XA-Wavenet-D",
    Richard: "ar-XA-Wavenet-B",
    Emily: "ar-XA-Wavenet-A",
    John: "ar-XA-Wavenet-C",
  },
};

const jawAssets = [
  "Afro_01_Jaw",
  "Afro_02_Jaw",
  "Afro_03_Jaw",
  "Arabic_01_Jaw",
  "Arabic_02_Jaw",
  "Arabic_03_Jaw",
  "Asian_01_Jaw",
  "Asian_02_Jaw",
  "Asian_03_Jaw",
  "Asian_04_Jaw",
  "Asian_05_Jaw",
  "Asian_06_Jaw",
  "Asian_07_Jaw",
  "Asian_08_Jaw",
  "Asian_09_Jaw",
  "Asian_10_Jaw",
  "Asian_11_Jaw",
  "Asian_12_Jaw",
  "Asian_13_Jaw",
  "Asian_14_Jaw",
  "Asian_15_Jaw",
  "Asian_16_Jaw",
  "Asian_17_Jaw",
  "Asian_18_Jaw",
  "Asian_19_Jaw",
  "Asian_20_Jaw",
  "Asian_21_Jaw",
  "Asian_22_Jaw",
  "Asian_23_Jaw",
  "Asian_24_Jaw",
  "Asian_25_Jaw",
  "Asian_26_Jaw",
  "Asian_27_Jaw",
  "Asian_28_Jaw",
  "Asian_29_Jaw",
  "Asian_30_Jaw",
  "Caucasian_01_Jaw",
  "Caucasian_02_Jaw",
  "Caucasian_03_Jaw",
  "Caucasian_04_Jaw",
  "Caucasian_05_Jaw",
  "Caucasian_06_Jaw",
  "Caucasian_07_Jaw",
  "Caucasian_08_Jaw",
  "Caucasian_09_Jaw",
  "Caucasian_10_Jaw",
  "Indian_01_Jaw",
  "Indian_02_Jaw",
  "Indian_03_Jaw",
  "Indigenous_01_Jaw",
  "Latin_01_Jaw",
  "Latin_02_Jaw",
  "Latin_03_Jaw",
  "Latin_04_Jaw",
  "Latin_05_Jaw",
  "Latin_06_Jaw",
  "Latin_07_Jaw",
  "Latin_08_Jaw",
  "Latin_09_Jaw",
];

const cheeksAssets = [
  "Afro_01_Cheeks",
  "Afro_02_Cheeks",
  "Afro_03_Cheeks",
  "Arabic_01_Cheeks",
  "Arabic_02_Cheeks",
  "Arabic_03_Cheeks",
  "Asian_01_Cheeks",
  "Asian_02_Cheeks",
  "Asian_03_Cheeks",
  "Asian_04_Cheeks",
  "Asian_05_Cheeks",
  "Asian_06_Cheeks",
  "Asian_07_Cheeks",
  "Asian_08_Cheeks",
  "Asian_09_Cheeks",
  "Asian_10_Cheeks",
  "Asian_11_Cheeks",
  "Asian_12_Cheeks",
  "Asian_13_Cheeks",
  "Asian_14_Cheeks",
  "Asian_15_Cheeks",
  "Asian_16_Cheeks",
  "Asian_17_Cheeks",
  "Asian_18_Cheeks",
  "Asian_19_Cheeks",
  "Asian_20_Cheeks",
  "Asian_21_Cheeks",
  "Asian_22_Cheeks",
  "Asian_23_Cheeks",
  "Asian_24_Cheeks",
  "Asian_25_Cheeks",
  "Asian_26_Cheeks",
  "Asian_27_Cheeks",
  "Asian_28_Cheeks",
  "Asian_29_Cheeks",
  "Asian_30_Cheeks",
  "Caucasian_01_Cheeks",
  "Caucasian_02_Cheeks",
  "Caucasian_03_Cheeks",
  "Caucasian_04_Cheeks",
  "Caucasian_05_Cheeks",
  "Caucasian_06_Cheeks",
  "Caucasian_07_Cheeks",
  "Caucasian_08_Cheeks",
  "Caucasian_09_Cheeks",
  "Caucasian_10_Cheeks",
  "Indian_01_Cheeks",
  "Indian_02_Cheeks",
  "Indian_03_Cheeks",
  "Indigenous_01_Cheeks",
  "Latin_01_Cheeks",
  "Latin_02_Cheeks",
  "Latin_03_Cheeks",
  "Latin_04_Cheeks",
  "Latin_05_Cheeks",
  "Latin_06_Cheeks",
  "Latin_07_Cheeks",
  "Latin_08_Cheeks",
  "Latin_09_Cheeks",
];

const mouthAssets = [
  "Afro_01_Mouth",
  "Afro_02_Mouth",
  "Afro_03_Mouth",
  "Arabic_01_Mouth",
  "Arabic_02_Mouth",
  "Arabic_03_Mouth",
  "Asian_01_Mouth",
  "Asian_02_Mouth",
  "Asian_03_Mouth",
  "Asian_04_Mouth",
  "Asian_05_Mouth",
  "Asian_06_Mouth",
  "Asian_07_Mouth",
  "Asian_08_Mouth",
  "Asian_09_Mouth",
  "Asian_10_Mouth",
  "Asian_11_Mouth",
  "Asian_12_Mouth",
  "Asian_13_Mouth",
  "Asian_14_Mouth",
  "Asian_15_Mouth",
  "Asian_16_Mouth",
  "Asian_17_Mouth",
  "Asian_18_Mouth",
  "Asian_19_Mouth",
  "Asian_20_Mouth",
  "Asian_21_Mouth",
  "Asian_22_Mouth",
  "Asian_23_Mouth",
  "Asian_24_Mouth",
  "Asian_25_Mouth",
  "Asian_26_Mouth",
  "Asian_27_Mouth",
  "Asian_28_Mouth",
  "Asian_29_Mouth",
  "Asian_30_Mouth",
  "Caucasian_01_Mouth",
  "Caucasian_02_Mouth",
  "Caucasian_03_Mouth",
  "Caucasian_04_Mouth",
  "Caucasian_05_Mouth",
  "Caucasian_06_Mouth",
  "Caucasian_07_Mouth",
  "Caucasian_08_Mouth",
  "Caucasian_09_Mouth",
  "Caucasian_10_Mouth",
  "Indian_01_Mouth",
  "Indian_02_Mouth",
  "Indian_03_Mouth",
  "Indigenous_01_Mouth",
  "Latin_01_Mouth",
  "Latin_02_Mouth",
  "Latin_03_Mouth",
  "Latin_04_Mouth",
  "Latin_05_Mouth",
  "Latin_06_Mouth",
  "Latin_07_Mouth",
  "Latin_08_Mouth",
  "Latin_09_Mouth",
];

const noseAssets = [
  "Afro_01_Nose",
  "Afro_02_Nose",
  "Arabic_01_Nose",
  "Arabic_02_Nose",
  "Asian_01_Nose",
  "Asian_02_Nose",
  "Asian_03_Nose",
  "Asian_04_Nose",
  "Asian_05_Nose",
  "Asian_06_Nose",
  "Asian_07_Nose",
  "Asian_08_Nose",
  "Caucasian_01_Nose",
  "Caucasian_02_Nose",
  "Caucasian_03_Nose",
  "Caucasian_04_Nose",
  "Caucasian_05_Nose",
  "Caucasian_06_Nose",
  "Indian_01_Nose",
  "Indian_02_Nose",
  "Indian_03_Nose",
  "Indigenous_01_Nose",
  "Latin_01_Nose",
  "Latin_02_Nose",
  "Latin_03_Nose",
  "Latin_04_Nose",
  "Latin_05_Nose",
  "Nose_001",
  "Nose_002",
  "Nose_003",
  "Nose_004",
  "Nose_005",
  "Nose_006",
  "Nose_007",
  "Nose_008",
  "Nose_009",
  "Nose_010",
  "Nose_011",
  "Nose_012",
  "Nose_013",
  "Nose_014",
  "Nose_015",
  "Nose_016",
  "Nose_017",
  "Nose_018",
  "Nose_019",
  "Nose_020",
  "Nose_021",
  "Nose_022",
  "Nose_023",
  "Nose_024",
  "Nose_025",
  "Nose_026",
  "Afro_03_Nose",
  "Afro_Nose_Variation_01",
  "Afro_Nose_Variation_02",
  "Afro_Nose_Variation_03",
  "Afro_Nose_Variation_05",
  "Afro_Nose_Variation_06",
  "Arabic_03_Nose",
  "Asian_09_Nose",
  "Asian_10_Nose",
  "Asian_11_Nose",
  "Asian_12_Nose",
  "Asian_13_Nose",
  "Asian_14_Nose",
  "Asian_15_Nose",
  "Asian_16_Nose",
  "Asian_17_Nose",
  "Asian_18_Nose",
  "Asian_19_Nose",
  "Asian_20_Nose",
  "Asian_21_Nose",
  "Asian_22_Nose",
  "Asian_23_Nose",
  "Asian_24_Nose",
  "Asian_25_Nose",
  "Asian_26_Nose",
  "Asian_27_Nose",
  "Asian_28_Nose",
  "Asian_29_Nose",
  "Asian_30_Nose",
  "Caucasian_07_Nose",
  "Caucasian_08_Nose",
  "Caucasian_09_Nose",
  "Caucasian_10_Nose",
  "Latin_06_Nose",
  "Latin_07_Nose",
  "Latin_08_Nose",
  "Latin_09_Nose",
];

// Randomize Ears
const earsAssets = [
  "Afro_01_Ears",
  "Afro_02_Ears",
  "Arabic_01_Ears",
  "Arabic_02_Ears",
  "Asian_01_Ears",
  "Asian_02_Ears",
  "Asian_03_Ears",
  "Asian_04_Ears",
  "Asian_05_Ears",
  "Asian_06_Ears",
  "Asian_07_Ears",
  "Asian_08_Ears",
  "Caucasian_01_Ears",
  "Caucasian_02_Ears",
  "Caucasian_03_Ears",
  "Caucasian_04_Ears",
  "Caucasian_05_Ears",
  "Caucasian_06_Ears",
  "Ear_001",
  "Ear_002",
  "Ear_003",
  "Ear_004",
  "Ear_005",
  "Indian_01_Ears",
  "Indian_02_Ears",
  "Indian_03_Ears",
  "Indigenous_01_Ears",
  "Latin_01_Ears",
  "Latin_02_Ears",
  "Latin_03_Ears",
  "Latin_04_Ears",
  "Latin_05_Ears",
  "Latin_06_Ears",
  "Latin_07_Ears",
  "Latin_08_Ears",
  "Latin_09_Ears",
];

const eyesAssets = [
  "Afro_01_Eyes",
  "Afro_02_Eyes",
  "Arabic_01_Eyes",
  "Arabic_02_Eyes",
  "Asian_01_Eyes",
  "Asian_02_Eyes",
  "Asian_03_Eyes",
  "Asian_04_Eyes",
  "Asian_05_Eyes",
  "Asian_06_Eyes",
  "Asian_07_Eyes",
  "Asian_08_Eyes",
  "Asian_09_Eyes",
  "Asian_10_Eyes",
  "Asian_11_Eyes",
  "Asian_12_Eyes",
  "Asian_13_Eyes",
  "Asian_14_Eyes",
  "Asian_15_Eyes",
  "Asian_16_Eyes",
  "Asian_17_Eyes",
  "Asian_18_Eyes",
  "Asian_19_Eyes",
  "Asian_20_Eyes",
  "Asian_21_Eyes",
  "Asian_22_Eyes",
  "Asian_23_Eyes",
  "Asian_24_Eyes",
  "Asian_25_Eyes",
  "Asian_26_Eyes",
  "Asian_27_Eyes",
  "Asian_28_Eyes",
  "Caucasian_02_Eyes",
  "Caucasian_03_Eyes",
  "Caucasian_04_Eyes",
  "Caucasian_05_Eyes",
  "Caucasian_06_Eyes",
  "Caucasian_07_Eyes",
  "Caucasian_08_Eyes",
  "Caucasian_09_Eyes",
  "Caucasian_10_Eyes",
  "Indian_01_Eyes",
  "Indian_02_Eyes",
  "Indian_03_Eyes",
  "Indigenous_01_Eyes",
  "Latin_01_Eyes",
  "Latin_02_Eyes",
  "Latin_03_Eyes",
  "Latin_04_Eyes",
  "Latin_05_Eyes",
  "Latin_06_Eyes",
  "Latin_07_Eyes",
  "Latin_08_Eyes",
  "Latin_09_Eyes",
];

const assets = {
  Age: {
    variations: [
      "Age_Variation_25_40_Var1",
      "Age_Variation_25_40_Var1_0",
      "Age_Variation_25_40_Var1_1",
      "Age_Variation_25_40_Var1_2",
      "Age_Variation_25_40_Var1_3",
      "Age_Variation_25_40_Var1_4",
      "Age_Variation_25_40_Var1_5",
      "Age_Variation_25_40_Var1_6",
    ],
    currentIndex: 0,
  },
  Rosacea: {
    variations: [
      "Rosacea_01",
      "Blushing_allover",
      "Blushing_Cheeks",
      "Blushing_FaceBottom",
      "Blushing_FullFace",
      "00_NoRosacea",
    ],
    currentIndex: 0,
  },
  Mole: {
    variations: ["Moles_01", "Moles_02", "No_Mole", "Moles_03"],
    currentIndex: 0,
  },
  Acne: {
    variations: ["Acne_01", "Acne_02", "Acne_03", "Acne_04"],
    currentIndex: 0,
  },
  Pimples: {
    variations: ["Pimples_01", "Pimples_02", "Pimples_03", "Pimples_04"],
    currentIndex: 0,
  },
  Freckles: {
    variations: [
      "Freckles_Variation_01",
      "Freckles_Variation_02",
      "Freckles_Variation_03",
      "Freckle_Variation_04",
      "Freckles_Variation_05",
      "Freckle_Variation_06",
      "Freckle_Variation_07",
    ],
    currentIndex: 0,
  },
  Stubble: {
    variations: ["Stubbles_Beard_Full_Diffuse"],
    currentIndex: 0,
  },
};

// List of slider IDs you want to include in the randomization
const sliderIds = [
  "ageButton",
  "rosaceaButton",
  "moleButton",
  "acneButton",
  "pimpelsButton",
  "frecklesButton",
];

const hairAssets = [
  "hair_08_v2",
  "Hair_Male_03",
  "Hair_Male_02",
  "Hair_Male_01",
  "Hair_Wavy_03",
  "Hair_Straight_02",
  "Hair_Wavy_02",
  "AB_Hair_04",
  "AB_Hair_03",
  "AB_Hair_02",
  "AB_Hair_01",
  "Hair_Wavy_01",
  "Hair_Straight_01",
  "High_ponytail",
  "DG",
  "Stephanie",
  "Afro",
  "Angel_braids",
  "Angel_ponytail",
  "Bi_Wen_Jin",
  "Brad_Pitt_Hair",
  "Buzzcut",
  "Crypto",
  "Cuban",
  "Curly",
  "Curly_Ponytail",
  "David_Schwarztz",
  "Dom",
  "Elon_Musk",
  "Gary_Vee",
  "Katy_Perry",
  "Livi",
  "Madonna_Hair",
  "Marilyn_Monroe",
  "Mason",
  "Max",
  "Natalia",
  "Peaky_Blinders_Hair",
  "Pixie_cut",
  "Sadaf",
  "Sisi",
  "Snoop_Dogg",
  "Suzanne",
  "Tijmen",
  "Wavy",
  "William",
  "Wolfcut",
  "Zuckerberg",
  "AliceHair",
  "CyberCut",
  "Lil_Miquela",
  "StraightBangs",
  "Mohawk",
  "Eva",
  "Hair_Straight_01",
  "Hair_Wavy_01",
  "AB_Hair_01",
];

// Randomizer for Eyebrows
const eyebrowAssets = [
  "No_Eyebrow",
  "Eyebrows_7",
  "Eyebrows_6",
  "Eyebrows_11",
  "Eyebrows_Unibrow_3",
  "Eyebrows_Name_10",
  "Eyebrows_Name_2",
  "Eyebrows_SadafJadran",
  "Eyebrows_SnoopDogg",
  "Eyebrows_Unibrow_1",
  "Eyebrows_Unibrow_2",
  "Eyebrows_Unibrow_4",
  "F_Brows_001",
  "F_Brows_002",
  "F_Brows_003",
  "F_Brows_004",
  "F_Brows_005",
  "M_Brows_001",
  "M_Brows_002",
  "M_Brows_003",
  "Brows_LessDense_01",
  "Brows_LessDense_02",
];

// Randomizer for Eyelashes
const eyelashAssets = [
  "Lashes_Short",
  "DefaultEyelashes",
  "Girly",
  "Alice_Eyelashes",
  "Eyelashes_Clumped_Lashes",
  "AB_Lashes_01",
];

// Randomizer for Mustache
const mustacheAssets = [
  "00_NO_Mustache",
  "Zorro",
  "Frenchfork_01",
  "mustache_Hook",
  "mustache_Horseshoe",
  "Straight_Mustaches",
  "Mustache_Chevron",
  "Mustache_Dali",
  "Mustache_Frenchfork_02",
  "Mustache_Gooate",
  "Mustache_Imperial",
  "Mustache_Vandyke",
  "Mustache_Vikinggoatee",
];

const beardAssets = [
  "00_NO_Beard",
  "Imperial",
  "beard_JohnDeaton",
  "beard_FrenchFork",
  "Beard_Brad_Garlinghouse",
  "Beard_Brad_Pitt",
  "Beard_David_Schwarztz",
  "Beard_Elon_Musk",
  "Beard_Farokh",
  "Beard_Frenchfork_Short",
  "Beard_Fullbeard",
  "Beard_Gooate_Chin_Beard",
  "Beard_JeremyHogan",
  "Beard_Long_Straight",
  "Beard_MartinHiesboeck",
  "Beard_Mason",
  "Beard_Muttonchops",
  "Beard_Panos",
  "Beard_SnoopDogg",
  "Beard_Soulpatch",
  "Beard_Vandyke",
  "Beard_Vandyke_Chin",
  "Beard_Vikinggoatee",
  "Beard_Zorro_Chin",
  "Beard_Stubble",
];

const haircardAssets = [
  "Hair01_cinematic",
  "Hair02_cinematic",
  "Hair03_cinematic",
  "Hair04_LumiaEve_cinematic",
  "Mesh_hair_style1",
  "Mesh_hair_style2",
];

const lipstickAssets = [
  "00_Lipstick",
  "Lipstick_01",
  "lipstick_02",
  "lipstick_Big",
  "lipstick_BigBlur",
  "lipstick_Gradient",
  "lipstick_HalfGradient",
  "lipstick_Outline",
  "Lipstick_Stylised_01",
  "Lipstick_Stylised_02",
  "lipstick_Symmetrical",
  "lipstick_UpperLip",
  "lipstick_03",
  "lipstick_04",
  "lipstick_Butterfly",
  "lipstick_Drip",
  "lipstick_Smudged",
];

const eyeShadowAssets = [
  "00_EyesShadow",
  "Eye_Shadow_SmokeyCatEye",
  "Shadow_2",
  "EyeShadow_Panda_Icon",
  "Preset_RedBlue",
];

const eyelinerAssets = [
  "00_EyesLine",
  "Simple",
  "Eyeliner_Droopy",
  "Eyeliner_Flick",
  "Eyeliner_SimpleLong",
  "Eyeliner_Double",
  "Eyeliner_Fox",
  "Eyeliner_DoubleFlick",
  "Eyeliner_Dramatic",
  "Eyeliner_GraphicLiner_02",
  "Eyeliner_Arabic",
  "Eyeliner_Triangle",
  "Eyeliner_Clown",
  "Eyeliner_Low",
  "Eyeliner_GraphicLiner_04",
];

// Randomize Facepaint
const facePaintAssets = [
  "NO_facePaint",
  "facePaint_Clown",
  "facePaint_Honey",
  "facePaint_Mermaid",
  "facePaint_Reindeer",
  "facePaint_SugarSkull",
  "facePaint_Tiger",
  "facePaint_Zebra",
  "facePaint_Amphibian",
  "facePaint_Avatar",
  "facePaint_Dog",
  "facePaint_Dragon",
  "facePaint_Goat",
  "facePaint_Monkey",
  "facePaint_Ox",
];

// Randomize Tattoos
const tattooAssets = [
  "NO_facePaint",
  "Preset_FaceTattoos",
  "facetattoo_maori",
  "Face_Tattoo_4",
  "Face_Tattoo_5",
  "Face_Tattoo_6",
  "Face_Tattoo_7",
  "Face_Tattoo_8",
];
// Randomize Iris Lens
const irisLensAssets = [
  "00_Lens",
  "Iris_Ocean",
  "Iris_Cyborg",
  "Iris_Ghost",
  "Iris_Heart",
  "Iris_Pentagram",
  "Iris_Smiley",
  "Iris_Snake",
  "Iris_Brown",
];

// Randomize Iris
const irisAssets = [
  "Iris_brown3",
  "iris_Brown",
  "Iris_blue2",
  "Iris_blue",
  "Iris_blue2_1",
  "Iris_blue2_2",
  "Iris_bluerazy",
  "Iris_brown2",
  "Iris_brown4",
  "Iris_Green",
  "Iris_green2",
  "Iris_greenY",
  "Iris_Brown5",
];
// Randomize Special
const specialAssets = [
  "NO_Special",
  "Cyber_1",
  "Cyberpunk_Cheek_Implant",
  "Cyberpunk_Face_Battery",
  "Cyberpunk_Face_Implants",
  "Cyberpunk_Hexagon_Implants",
  "Cyberpunk_Horizontal_Implants",
  "Cyberpunk_Jaw",
  "Cyberpunk_Metal_Implants",
  "Fantasy_Gold_Armor",
];
